//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class weatherdata {
    
    private weatherdataMetaModel[][] metaField;
    
    private weatherdataProduct[] productField;
    
    private string createdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("model", typeof(weatherdataMetaModel), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public weatherdataMetaModel[][] meta {
        get {
            return this.metaField;
        }
        set {
            this.metaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("product", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProduct[] product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataMetaModel {
    
    private string nameField;
    
    private string terminField;
    
    private string runendedField;
    
    private string nextrunField;
    
    private string fromField;
    
    private string toField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string termin {
        get {
            return this.terminField;
        }
        set {
            this.terminField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string runended {
        get {
            return this.runendedField;
        }
        set {
            this.runendedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextrun {
        get {
            return this.nextrunField;
        }
        set {
            this.nextrunField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProduct {
    
    private weatherdataProductTime[] timeField;
    
    private string classField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTime[] time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTime {
    
    private weatherdataProductTimeLocation[] locationField;
    
    private string datatypeField;
    
    private string fromField;
    
    private string toField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocation[] location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datatype {
        get {
            return this.datatypeField;
        }
        set {
            this.datatypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocation {
    
    private weatherdataProductTimeLocationPrecipitation[] precipitationField;
    
    private weatherdataProductTimeLocationMinTemperature[] minTemperatureField;
    
    private weatherdataProductTimeLocationMaxTemperature[] maxTemperatureField;
    
    private weatherdataProductTimeLocationSymbol[] symbolField;
    
    private weatherdataProductTimeLocationSymbolProbability[] symbolProbabilityField;
    
    private weatherdataProductTimeLocationTemperature[] temperatureField;
    
    private weatherdataProductTimeLocationWindDirection[] windDirectionField;
    
    private weatherdataProductTimeLocationWindSpeed[] windSpeedField;
    
    private weatherdataProductTimeLocationWindGust[] windGustField;
    
    private weatherdataProductTimeLocationHumidity[] humidityField;
    
    private weatherdataProductTimeLocationPressure[] pressureField;
    
    private weatherdataProductTimeLocationCloudiness[] cloudinessField;
    
    private weatherdataProductTimeLocationFog[] fogField;
    
    private weatherdataProductTimeLocationLowClouds[] lowCloudsField;
    
    private weatherdataProductTimeLocationMediumClouds[] mediumCloudsField;
    
    private weatherdataProductTimeLocationHighClouds[] highCloudsField;
    
    private weatherdataProductTimeLocationTemperatureProbability[] temperatureProbabilityField;
    
    private weatherdataProductTimeLocationWindProbability[] windProbabilityField;
    
    private weatherdataProductTimeLocationDewpointTemperature[] dewpointTemperatureField;

    private weatherdataProductTimeLocationUV[] uvField;

    private string altitudeField;
    
    private string latitudeField;
    
    private string longitudeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("precipitation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationPrecipitation[] precipitation {
        get {
            return this.precipitationField;
        }
        set {
            this.precipitationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("minTemperature", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationMinTemperature[] minTemperature {
        get {
            return this.minTemperatureField;
        }
        set {
            this.minTemperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("maxTemperature", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationMaxTemperature[] maxTemperature {
        get {
            return this.maxTemperatureField;
        }
        set {
            this.maxTemperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("symbol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationSymbol[] symbol {
        get {
            return this.symbolField;
        }
        set {
            this.symbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("symbolProbability", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationSymbolProbability[] symbolProbability {
        get {
            return this.symbolProbabilityField;
        }
        set {
            this.symbolProbabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("temperature", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationTemperature[] temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("windDirection", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationWindDirection[] windDirection {
        get {
            return this.windDirectionField;
        }
        set {
            this.windDirectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("windSpeed", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationWindSpeed[] windSpeed {
        get {
            return this.windSpeedField;
        }
        set {
            this.windSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("windGust", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationWindGust[] windGust {
        get {
            return this.windGustField;
        }
        set {
            this.windGustField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("humidity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationHumidity[] humidity {
        get {
            return this.humidityField;
        }
        set {
            this.humidityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pressure", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationPressure[] pressure {
        get {
            return this.pressureField;
        }
        set {
            this.pressureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cloudiness", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationCloudiness[] cloudiness {
        get {
            return this.cloudinessField;
        }
        set {
            this.cloudinessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fog", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationFog[] fog {
        get {
            return this.fogField;
        }
        set {
            this.fogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lowClouds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationLowClouds[] lowClouds {
        get {
            return this.lowCloudsField;
        }
        set {
            this.lowCloudsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mediumClouds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationMediumClouds[] mediumClouds {
        get {
            return this.mediumCloudsField;
        }
        set {
            this.mediumCloudsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("highClouds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationHighClouds[] highClouds {
        get {
            return this.highCloudsField;
        }
        set {
            this.highCloudsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("temperatureProbability", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationTemperatureProbability[] temperatureProbability {
        get {
            return this.temperatureProbabilityField;
        }
        set {
            this.temperatureProbabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("windProbability", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationWindProbability[] windProbability {
        get {
            return this.windProbabilityField;
        }
        set {
            this.windProbabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dewpointTemperature", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationDewpointTemperature[] dewpointTemperature {
        get {
            return this.dewpointTemperatureField;
        }
        set {
            this.dewpointTemperatureField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uv", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUV[] uv
    {
        get
        {
            return this.uvField;
        }
        set
        {
            this.uvField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string altitude {
        get {
            return this.altitudeField;
        }
        set {
            this.altitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationPrecipitation {
    
    private string unitField;
    
    private string valueField;
    
    private string minvalueField;
    
    private string maxvalueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minvalue {
        get {
            return this.minvalueField;
        }
        set {
            this.minvalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxvalue {
        get {
            return this.maxvalueField;
        }
        set {
            this.maxvalueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationMinTemperature {
    
    private string idField;
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationMaxTemperature {
    
    private string idField;
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationSymbol {
    
    private string idField;
    
    private string numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationSymbolProbability {
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationTemperature {
    
    private string idField;
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationWindDirection {
    
    private string idField;
    
    private string degField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string deg {
        get {
            return this.degField;
        }
        set {
            this.degField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationWindSpeed {
    
    private string idField;
    
    private string mpsField;
    
    private string beaufortField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mps {
        get {
            return this.mpsField;
        }
        set {
            this.mpsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string beaufort {
        get {
            return this.beaufortField;
        }
        set {
            this.beaufortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationWindGust {
    
    private string idField;
    
    private string mpsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mps {
        get {
            return this.mpsField;
        }
        set {
            this.mpsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationHumidity {
    
    private string valueField;
    
    private string unitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationPressure {
    
    private string idField;
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationCloudiness {
    
    private string idField;
    
    private string percentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent {
        get {
            return this.percentField;
        }
        set {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationFog {
    
    private string idField;
    
    private string percentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent {
        get {
            return this.percentField;
        }
        set {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationLowClouds {
    
    private string idField;
    
    private string percentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent {
        get {
            return this.percentField;
        }
        set {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationMediumClouds {
    
    private string idField;
    
    private string percentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent {
        get {
            return this.percentField;
        }
        set {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationHighClouds {
    
    private string idField;
    
    private string percentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent {
        get {
            return this.percentField;
        }
        set {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationTemperatureProbability {
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationWindProbability {
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUV
{

    private weatherdataProductTimeLocationUVUvi_clear[] uvi_clearField;

    private weatherdataProductTimeLocationUVUvi_partly_cloudy[] uvi_partly_cloudyField;

    private weatherdataProductTimeLocationUVUvi_cloudy[] uvi_cloudyField;

    private weatherdataProductTimeLocationUVUvi_forecast[] uvi_forecastField;

    private weatherdataProductTimeLocationUVOzon[] ozonField;

    private weatherdataProductTimeLocationUVSnowcover[] snowcoverField;

    private weatherdataProductTimeLocationUVCloud_cover[] cloud_coverField;

    private weatherdataProductTimeLocationUVAlbedo[] albedoField;

    private weatherdataProductTimeLocationUVSolar_zenith[] solar_zenithField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uvi_clear", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVUvi_clear[] uvi_clear
    {
        get
        {
            return this.uvi_clearField;
        }
        set
        {
            this.uvi_clearField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uvi_partly_cloudy", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVUvi_partly_cloudy[] uvi_partly_cloudy
    {
        get
        {
            return this.uvi_partly_cloudyField;
        }
        set
        {
            this.uvi_partly_cloudyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uvi_cloudy", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVUvi_cloudy[] uvi_cloudy
    {
        get
        {
            return this.uvi_cloudyField;
        }
        set
        {
            this.uvi_cloudyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uvi_forecast", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVUvi_forecast[] uvi_forecast
    {
        get
        {
            return this.uvi_forecastField;
        }
        set
        {
            this.uvi_forecastField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ozon", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVOzon[] ozon
    {
        get
        {
            return this.ozonField;
        }
        set
        {
            this.ozonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("snowcover", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVSnowcover[] snowcover
    {
        get
        {
            return this.snowcoverField;
        }
        set
        {
            this.snowcoverField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cloud_cover", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVCloud_cover[] cloud_cover
    {
        get
        {
            return this.cloud_coverField;
        }
        set
        {
            this.cloud_coverField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("albedo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVAlbedo[] albedo
    {
        get
        {
            return this.albedoField;
        }
        set
        {
            this.albedoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("solar_zenith", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public weatherdataProductTimeLocationUVSolar_zenith[] solar_zenith
    {
        get
        {
            return this.solar_zenithField;
        }
        set
        {
            this.solar_zenithField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVUvi_clear
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVUvi_partly_cloudy
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVUvi_cloudy
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVUvi_forecast
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVOzon
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVSnowcover
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVCloud_cover
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVAlbedo
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class weatherdataProductTimeLocationUVSolar_zenith
{

    private string unitField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class weatherdataProductTimeLocationDewpointTemperature {
    
    private string idField;
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.57.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private weatherdata[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("weatherdata")]
    public weatherdata[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
